version: "2"
services:
  ak-solr:
    image: acdhch/aksearch-solr
    volumes:
      - C:\dev\data\AkSearchWeb\solr-logs:/opt/solr/server/logs
      - C:\dev\data\AkSearchWeb\solr-cores:/opt/solr/server/solr
      - C:\dev\AkSearchWeb\local\harvest:/opt/harvest
      - C:\dev\AkSearchSolr\local\:/opt/local
    ports:
      - "8983:8983"
    networks:
      - backend
      - bridge
  ak-mysql:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
    volumes:
      - ak-mysql:/var/lib/mysql
    networks:
      - backend
  ak-web:
    image: acdhch/aksearch-web
    environment:
      - DB_PSWD=zxcasd
      - DB_HOST=ak-mysql
      - DB_ROOT_PSWD=123qwe
      - SOLR_URL=http://ak-solr:8983/solr
      - ALMA_KEY=l8xxd31454cd4ee64cac8523db95803b211f
      - VUFIND_LOCAL_MODULES=AkSearch,AkSearchApi,AkSearchConsole,AkSearchSearch,aksearchExt
      - APPLICATION_ENV=testing
    ports:
      - "80:80"
    volumes:
      - C:\dev\AkSearchWeb\local\:/var/www/local
    networks:
      - backend
      - bridge
    depends_on:
      - ak-mysql
networks:
  backend:
    driver: bridge
  bridge:
volumes:
  ak-solrlogs:
  ak-solrdata:
  ak-mysql:
  ak-harvest:

