services:
  ak-solr:
    image: acdhch/aksearch-solr:vufind10
    volumes:
    - ak-solrlogs:/opt/solr/server/logs
    - ak-solrdata:/opt/solr/server/solr
    - ak-harvest:/opt/harvest/alma
    - ak-harvest-degruyter:/opt/harvest/degruyter
    ports:
    - "8983:8983"
    networks:
    - backend
  ak-mysql:
    image: mariadb:10
    environment:
    - MYSQL_ROOT_PASSWORD=123qwe
    volumes:
    - ak-mysql:/var/lib/mysql
    networks:
    - backend
  ak-web:
    image: acdhch/aksearch-web:vufind10
    environment:
    - DB_PSWD=zxcasd
    - DB_HOST=ak-mysql
    - DB_ROOT_PSWD=123qwe
    - SOLR_URL=http://localdeployment-ak-solr-1:8983/solr
    - ALMA_KEY=xxx
    - VUFIND_LOCAL_MODULES=AkSearch,AkSearchApi,AkSearchConsole,AkSearchSearch,aksearchExt
    - APPLICATION_ENV=development
    ports:
    - "80:80"
    volumes:
    - ak-harvest:/var/www/local/harvest/alma
    - ak-harvest-degruyter:/var/www/local/harvest/degruyter
    #- ../AkSearchWeb/local:/var/www/local
    #- ../AkSearchExtend:/usr/local/vufind/vendor/acdh-oeaw/aksearch-ext
    #- ../AkSearchAcdhTheme:/usr/local/vufind/themes/AcdhchTheme
    networks:
    - backend
    - bridge
    depends_on:
    - ak-mysql
networks:
  backend:
    driver: bridge
  bridge:
volumes:
  ak-solrlogs:
  ak-solrdata:
  ak-mysql:
  ak-harvest:
  ak-harvest-degruyter:
