name: phpunit

on: push

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: docker build -t acdhch/aksearchweb:latest .
    - name: docker push
      run: |
        echo docker "${{ secrets.DOCKERHUBTOKEN }}" | sudo login -u zozlak --password-stdin
        sudo docker push acdhch/aksearch-web
