name: phpunit

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      run: docker build -t acdhch/aksearchweb:latest .
    - name: docker push
      run: |
        docker login -u zozlak -p "${{ secrets.DOCKERHUBTOKEN }}" 
        docker push acdhch/aksearch-web
