name: build and publish docker image
on:
  push:
    branches: [main, dev]
  workflow_dispatch: ~

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get branch
      run: |
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        TAG=${GITHUB_REF##*/}
        if [ "$TAG" == "main" ] ; then TAG=latest ; fi
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: docker build
      run: docker build -t acdhch/aksearch-web:$TAG --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" .
    - uses: docker/login-action@v1
      with:
        username: zozlak
        password: ${{ secrets.DOCKERHUBTOKEN }}
    - name: docker push
      run: docker push acdhch/aksearch-web:$TAG
    - name: redeploy
      run: |
        NMSP=oeaw-resources-dev
        if [ "$TAG" == "main"] ; then
          NMSP=oeaw-resources
        fi
        curl -X POST -H "Authorization: Bearer ${{ secrets.RANCHER_TOKEN }}" "https://rancher.acdh-dev.oeaw.ac.at/p/c-zdbh8:p-dw4vh/workload/deployment:$NMSP:web?action=redeploy"

